### PR TITLE
Add TFM netstandard2.0

### LINKED ISSUE #149: support netstandard 2.0
I want to use markdig and this extensions in Source Generators.

### PR DESCRIPTION
**Pull request by ElderJames**
## Description

closed #149 

## Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](https://github.com/wbaldoumas/markdown-colorcode/blob/main/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

### CODE REVIEW

**Comment by wbaldoumas** [comment]
See my comment on the linked issue [here](https://github.com/wbaldoumas/markdown-colorcode/issues/149#issuecomment-2231455763) regarding needing .NET Standard 2.0 support from one of the packages that this package depends on.

**Comment by ElderJames** [comment]
Hello @wbaldoumas , I have revert the changes for unsupported library.

**Comment by wbaldoumas** [comment]
> Hello @wbaldoumas , I have revert the changes for unsupported library.

Thanks. It still looks like the restore is failing in the pipelines here for the build and test step. Please address that and I will re-run the pipelines for you.

**Comment by ElderJames** [comment]
@wbaldoumas OK, I reverted the tests.

**Review by wbaldoumas — APPROVED** [review]

**Pull request merged**
